# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages


before_install:
  - sudo apt-get update
  - sudo apt-get install libgdal-dev libproj-dev

r:
 - oldrel
 - release
 - devel
 
r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'
